
// data.js - Configuración y Banco de 500 Temas para CRUST

const CONFIG = {
    minimumStudyMinutes: 45,
    protectorHoursRequired: 3,
    maxProtectors: 3,
    protectorCooldownDays: 7
};

const TOPICS = [
    // --- ASTRONOMÍA Y COSMOLOGÍA (30) ---
    { id: "fermi", name: "La paradoja de Fermi", category: "Astronomía" },
    { id: "agujeros_negros", name: "Agujeros Negros y Singularidades", category: "Astronomía" },
    { id: "big_bang", name: "La teoría del Big Bang", category: "Astronomía" },
    { id: "radiacion_fondo", name: "Radiación de Fondo de Microondas", category: "Astronomía" },
    { id: "materia_oscura", name: "Materia y Energía Oscura", category: "Astronomía" },
    { id: "exoplanetas", name: "Métodos de Detección de Exoplanetas", category: "Astronomía" },
    { id: "estrellas_neutrones", name: "Estrellas de Neutrones y Púlsares", category: "Astronomía" },
    { id: "supernovas", name: "Tipos de Supernovas y Nucleosíntesis", category: "Astronomía" },
    { id: "expansion_universo", name: "La Ley de Hubble y la Expansión del Universo", category: "Astronomía" },
    { id: "horizonte_sucesos", name: "El Horizonte de Sucesos y Radiación de Hawking", category: "Astronomía" },
    { id: "sistema_solar_formacion", name: "Formación e Hipótesis Nebular del Sistema Solar", category: "Astronomía" },
    { id: "cinturon_kuiper", name: "El Cinturón de Kuiper y la Nube de Oort", category: "Astronomía" },
    { id: "telescopio_james_webb", name: "Óptica e Descubrimientos del Telescopio James Webb", category: "Astronomía" },
    { id: "espectroscopia_astronomica", name: "Espectroscopía y Composición Estelar", category: "Astronomía" },
    { id: "cuasares", name: "Cuásares y Núcleos Galácticos Activos", category: "Astronomía" },
    { id: "galaxia_andromeda", name: "La Colisión Vía Láctea - Andrómeda", category: "Astronomía" },
    { id: "escala_kardashev", name: "La Escala de Kardashev", category: "Astronomía" },
    { id: "ondas_gravitacionales", name: "Ondas Gravitacionales y Colisiones de Agujeros Negros", category: "Astronomía" },
    { id: "vida_extraterrestre_biofirmas", name: "Biofirmas en Atmósferas Exoplanetarias", category: "Astronomía" },
    { id: "diagrama_hr", name: "El Diagrama Hertzsprung-Russell", category: "Astronomía" },
    { id: "viento_solar", name: "Viento Solar y Tormentas Geomagnéticas", category: "Astronomía" },
    { id: "lunas_galileanas", name: "Las Lunas Galileanas de Júpiter", category: "Astronomía" },
    { id: "encelado_europa", name: "Océanos Subterráneos en Europa y Encélado", category: "Astronomía" },
    { id: "lente_gravitacional", name: "Lentes Gravitacionales y Teoría de la Relatividad", category: "Astronomía" },
    { id: "multiverso", name: "Modelos Teóricos de Multiverso", category: "Astronomía" },
    { id: "muerte_termica", name: "La Muerte Térmica del Universo (Big Freeze)", category: "Astronomía" },
    { id: "constelaciones_zodiaco", name: "Origen Cartográfico de las Constelaciones", category: "Astronomía" },
    { id: "asteroides_neo", name: "Objetos Cercanos a la Tierra y Defensa Planetaria", category: "Astronomía" },
    { id: "sol_ciclo_22", name: "El Ciclo de Dinamo Solar de 11 Años", category: "Astronomía" },
    { id: "gran_atractor", name: "El Gran Atractor y Supercúmulo Laniakea", category: "Astronomía" },

    // --- FÍSICA (30) ---
    { id: "relatividad_especial", name: "Relatividad Especial de Einstein", category: "Física" },
    { id: "relatividad_general", name: "Relatividad General y Curvatura del Espaciotiempo", category: "Física" },
    { id: "efecto_fotoelectrico", name: "El Efecto Fotoeléctrico", category: "Física" },
    { id: "mecanica_cuantica_gatos", name: "El Experimento del Gato de Schrödinger", category: "Física" },
    { id: "doble_rendija", name: "El Experimento de la Doble Rendija", category: "Física" },
    { id: "entropia_leyes", name: "Entropía y las Leyes de la Termodinámica", category: "Física" },
    { id: "modelo_estandar", name: "El Modelo Estándar de la Física de Partículas", category: "Física" },
    { id: "boson_higgs", name: "El Bosón de Higgs y el Campo de Higgs", category: "Física" },
    { id: "superconductividad", name: "Superconductividad y Efecto Meissner", category: "Física" },
    { id: "mecanica_fluidos", name: "Ecuaciones de Navier-Stokes y Dinámica de Fluidos", category: "Física" },
    { id: "optica_cuantica", name: "Entrelazamiento Cuántico y Paradoja EPR", category: "Física" },
    { id: "electromagnetismo_maxwell", name: "Las Ecuaciones de Maxwell", category: "Física" },
    { id: "teoria_cuerdas", name: "Introducción a la Teoría de Cuerdas", category: "Física" },
    { id: "gravedad_cuantica", name: "Gravedad Cuántica de Bucles", category: "Física" },
    { id: "efecto_doppler", name: "El Efecto Doppler", category: "Física" },
    { id: "fision_fusion_nuclear", name: "Fusión Nuclear vs Fisión Nuclear", category: "Física" },
    { id: "principio_incertidumbre", name: "Principio de Incertidumbre de Heisenberg", category: "Física" },
    { id: "antimateria", name: "Antimateria y Asimetría Materia-Antimateria", category: "Física" },
    { id: "plasma_cuarto_estado", name: "El Estado de Plasma y Confinamiento Magnético", category: "Física" },
    { id: "condensado_bose_einstein", name: "Condensado de Bose-Einstein", category: "Física" },
    { id: "teoria_caos", name: "Teoría del Caos y el Efecto Mariposa", category: "Física" },
    { id: "radiacion_cuerpo_negro", name: "Ley de Planck y la Catástrofe Ultravioleta", category: "Física" },
    { id: "péndulo_foucault", name: "El Péndulo de Foucault y Rotación Terrestre", category: "Física" },
    { id: "efecto_túnel", name: "Efecto Túnel Cuántico", category: "Física" },
    { id: "termodinamica_no_equilibrio", name: "Estructuras Disipativas de Ilya Prigogine", category: "Física" },
    { id: "velocidad_luz", name: "Constante c y Mediciones Históricas de la Luz", category: "Física" },
    { id: "física_acústica", name: "Ondas Sonoras, Resonancia y Cimática", category: "Física" },
    { id: "efecto_cherenkov", name: "Radiación Cherenkov", category: "Física" },
    { id: "semiconductores", name: "Física de Semiconductores y Uniones P-N", category: "Física" },
    { id: "conservacion_simetria", name: "El Teorema de Noether", category: "Física" },

    // --- QUÍMICA (25) ---
    { id: "tabla_periodica_historia", name: "Evolución de la Tabla Periódica", category: "Química" },
    { id: "enlaces_quimicos", name: "Enlaces Covalentes, Iónicos y Metálicos", category: "Química" },
    { id: "estequiometria", name: "Principios de Estequiometría y Balanceo", category: "Química" },
    { id: "quimica_organica_funcional", name: "Grupos Funcionales en Química Orgánica", category: "Química" },
    { id: "termoquimica", name: "Entalpía, Entropía y Energía Libre de Gibbs", category: "Química" },
    { id: "catalizadores", name: "Cinética Química y Mecanismos de Catálisis", category: "Química" },
    { id: "electroquimica", name: "Celdas Galvánicas y Baterías de Litio", category: "Química" },
    { id: "polimeros_sinteticos", name: "Química de Polímeros y Plásticos", category: "Química" },
    { id: "bioquimica_enzimas", name: "Estructura y Cinética Enzimática", category: "Química" },
    { id: "acidos_bases", name: "Teorías de Ácidos y Bases (pH y Escalas)", category: "Química" },
    { id: "espectrometria_masas", name: "Espectrometría de Masas y RMN", category: "Química" },
    { id: "quimica_atmosferica", name: "Capa de Ozono y Clorofluorocarbonos", category: "Química" },
    { id: "nanomateriales", name: "Grafeno y Nanotubos de Carbono", category: "Química" },
    { id: "radioactividad_decaimiento", name: "Isótopos y Decaimiento Radioactivo", category: "Química" },
    { id: "quimica_materia_condensada", name: "Estructuras Cristalinas y Redes de Bravais", category: "Química" },
    { id: "proceso_haber_bosch", name: "El Proceso Haber-Bosch y Fertilizantes", category: "Química" },
    { id: "quimica_verde", name: "Los 12 Principios de la Química Verde", category: "Química" },
    { id: "quimiopercepcion", name: "Bioquímica del Olfato y el Gusto", category: "Química" },
    { id: "alquimia_historia", name: "De la Alquimia a la Química Moderna", category: "Química" },
    { id: "elementos_transuranicos", name: "Síntesis de Elementos Transuránicos", category: "Química" },
    { id: "fotocatalisis", name: "Fotocatálisis y Producción de Hidrógeno", category: "Química" },
    { id: "química_forense", name: "Análisis Químico Forense y Toxicología", category: "Química" },
    { id: "supramolecular", name: "Química Supramolecular y Máquinas Moleculares", category: "Química" },
    { id: "radicales_libres", name: "Estrés Oxidativo y Antioxidantes", category: "Química" },
    { id: "destilacion_petroleo", name: "Refinación del Petróleo y Craqueo Químico", category: "Química" },

    // --- BIOLOGÍA Y BIOTECNOLOGÍA (35) ---
    { id: "crispr", name: "Edición Genética CRISPR-Cas9", category: "Biología" },
    { id: "fotosintesis", name: "Mecanismo Bioquímico de la Fotosíntesis", category: "Biología" },
    { id: "adn_replicacion", name: "Estructura y Replicación del ADN", category: "Biología" },
    { id: "epigenetica", name: "Epigenética y Modificación de Histonas", category: "Biología" },
    { id: "seleccion_natural", name: "Teoría de la Evolución por Selección Natural", category: "Biología" },
    { id: "microbioma_humano", name: "El Microbioma Intestinal y el Eje Creado", category: "Biología" },
    { id: "respiracion_celular", name: "El Ciclo de Krebs y Fosforilación Oxidativa", category: "Biología" },
    { id: "mitocondrias_origen", name: "Teoría Endosimbiótica de las Mitocondrias", category: "Biología" },
    { id: "sistema_inmune", name: "Inmunidad Innata vs Inmunidad Adaptativa", category: "Biología" },
    { id: "biologia_sintetica", name: "Diseño Genómico en Biología Sintética", category: "Biología" },
    { id: "telomeros_envejecimiento", name: "Telómeros y Biología del Envejecimiento", category: "Biología" },
    { id: "celulas_madre", name: "Células Madre Pluripotentes Inducidas (iPSC)", category: "Biología" },
    { id: "fagocitosis_autofagia", name: "Mecanismos de Autofagia Celular", category: "Biología" },
    { id: "ecologia_trofica", name: "Redes Tróficas y Cascadas Tróficas", category: "Biología" },
    { id: "bacteriofagos", name: "Fagoterapia y Virus Bacteriófagos", category: "Biología" },
    { id: "extinciones_masivas", name: "Las 5 Grandes Extinciones de la Tierra", category: "Biología" },
    { id: "comunicacion_plantas", name: "Micorrizas y Redes de Comunicación en Plantas", category: "Biología" },
    { id: "priones", name: "Proteínas Prionicas y Encefalopatías Spongiformes", category: "Biología" },
    { id: "embriologia", name: "Gastrulació y Desarrollo Embriológico", category: "Biología" },
    { id: "bioluminiscencia", name: "Mecanismo Moleculares de la Bioluminiscencia", category: "Biología" },
    { id: "virus_arn", name: "Mecanismo de Replicación de Virus ARN", category: "Biología" },
    { id: "taxonomia_cladistica", name: "Principios de Cladística y Filogenia", category: "Biología" },
    { id: "comportamiento_animal", name: "Sistemas de Apareamiento y Etología", category: "Biología" },
    { id: "ecofisiologia_extremofilos", name: "Microorganismos Extremófilos y Astrobiología", category: "Biología" },
    { id: "simbiosis_coral", name: "Blanqueamiento del Coral y Dinoflagelados", category: "Biología" },
    { id: "clonación_animal", name: "Técnicas de Transferencia Nuclear Celular", category: "Biología" },
    { id: "expresion_genica", name: "Transcripción, Traducción y ARN Mensajero", category: "Biología" },
    { id: "biomas_terrestres", name: "Ecosistemas y Dinámica de Biomas Globales", category: "Biología" },
    { id: "reloj_circadiano", name: "Genética de los Ritmos Circadianos", category: "Biología" },
    { id: "resistencia_antibioticos", name: "Mecanismos de Resistencia Bacteriana", category: "Biología" },
    { id: "efecto_bottleneck", name: "Deriva Genética y Efecto Fundador", category: "Biología" },
    { id: "zoologia_cefalopodos", name: "Neurobiología y Camuflaje en Cefalópodos", category: "Biología" },
    { id: "especiacion", name: "Especiación Alopátrica, Simpátrica y Parapátrica", category: "Biología" },
    { id: "secuenciacion_dna", name: "Sanger vs Secuenciación de Nueva Generación (NGS)", category: "Biología" },
    { id: "metabolismo_secundario", name: "Alcaloides y Flavonoides en Vegetales", category: "Biología" },

    // --- NEUROCIENCIA Y MEDICINA (25) ---
    { id: "potencial_accion", name: "El Potencial de Acción Neuronal", category: "Neurociencia" },
    { id: "neuroplasticidad", name: "Neuroplasticidad Sináptica y Aprendizaje", category: "Neurociencia" },
    { id: "neurotransmisores", name: "Dopamina, Serotonina y GABA", category: "Neurociencia" },
    { id: "corteza_prefrontal", name: "Anatomía de la Corteza Prefrontal y Funciones Ejecutivas", category: "Neurociencia" },
    { id: "sistema_limbico", name: "La Amígdala y la Procesación Emocional", category: "Neurociencia" },
    { id: "hipocampo_memoria", name: "Consolidación de la Memoria en el Hipocampo", category: "Neurociencia" },
    { id: "red_neuronal_por_defecto", name: "La Red Neuronal por Defecto (DMN)", category: "Neurociencia" },
    { id: "fases_sueño_rem", name: "Neurobiología del Sueño y Fases REM", category: "Neurociencia" },
    { id: "neuronas_espejo", name: "Neuronas Espejo y Empatía", category: "Neurociencia" },
    { id: "barrera_hematoencefalica", name: "Anatomía de la Barrera Hematoencefálica", category: "Neurociencia" },
    { id: "mielinizacion", name: "Células Gliales y Conducción Saltatoria", category: "Neurociencia" },
    { id: "fisiologia_dolor", name: "Vías Nociceptivas y Teoría de la Compuerta", category: "Neurociencia" },
    { id: "enfermedad_alzheimer", name: "Placas Beta-Amiloide y Proteína Tau", category: "Neurociencia" },
    { id: "enfermedad_parkinson", name: "Degeneración en la Sustancia Negra y Vía Nigroestriada", category: "Neurociencia" },
    { id: "interfaz_cerebro_computadora", name: "Neurotecnología e Interfaces BCI", category: "Neurociencia" },
    { id: "eeg_fmri", name: "Técnicas de Neuroimagen: EEG vs fMRI", category: "Neurociencia" },
    { id: "lateralizacion_cerebral", name: "Especialización Hemisférica Corporal", category: "Neurociencia" },
    { id: "neurogenesis_adulta", name: "Neurogénecis en la Zona Subgranular", category: "Neurociencia" },
    { id: "efecto_placebo", name: "Neurobiología del Efecto Placebo", category: "Neurociencia" },
    { id: "farmacologia_psiquiatrica", name: "Mecanismo de los Antidepresivos ISRS", category: "Neurociencia" },
    { id: "sistema_nervioso_autonomo", name: "Simpático vs Parasimpático y Nervio Vago", category: "Neurociencia" },
    { id: "afasias_lenguaje", name: "Área de Broca y Área de Wernicke", category: "Neurociencia" },
    { id: "adicion_recompensa", name: "La Vía Mesolímbica y el Circuito de Recompensa", category: "Neurociencia" },
    { id: "propiocepcion", name: "Propiocepción y Sistema Vestibular", category: "Neurociencia" },
    { id: "conciencia_teorias", name: "Teoría de la Información Integrada (IIT) y la Conciencia", category: "Neurociencia" },

    // --- MATEMÁTICAS Y LÓGICA (30) ---
    { id: "teoria_juegos", name: "Equilibrio de Nash y Teoría de Juegos", category: "Matemáticas" },
    { id: "teorema_incompletitud", name: "Teoremas de Incompletitud de Gödel", category: "Matemáticas" },
    { id: "hipotesis_riemann", name: "La Hipótesis de Riemann y Números Primos", category: "Matemáticas" },
    { id: "calculo_infinitesimal", name: "Historia del Cálculo: Newton vs Leibniz", category: "Matemáticas" },
    { id: "geometria_no_euclidiana", name: "Geometría Hiperbólica y Elíptica", category: "Matemáticas" },
    { id: "fractales_mandelbrot", name: "Conjunto de Mandelbrot y Geometría Fractal", category: "Matemáticas" },
    { id: "teorema_bayes", name: "Inferencia Bayesiana y Probabilidad Condicional", category: "Matemáticas" },
    { id: "ultimo_teorema_fermat", name: "La Demostración del Último Teorema de Fermat", category: "Matemáticas" },
    { id: "topologia_poincare", name: "Topología y la Conjetura de Poincaré", category: "Matemáticas" },
    { id: "sucesion_fibonacci", name: "Sucesión de Fibonacci y la Proporción Áurea", category: "Matemáticas" },
    { id: "algebra_lineal_autovectores", name: "Autovalores, Autovectores y Transformaciones", category: "Matemáticas" },
    { id: "teoria_grafos", name: "El Problema de los Puentes de Königsberg", category: "Matemáticas" },
    { id: "problema_p_np", name: "Clases de Complejidad P vs NP", category: "Matemáticas" },
    { id: "transformada_fourier", name: "La Transformada de Fourier", category: "Matemáticas" },
    { id: "teoria_conjuntos_cantor", name: "Paradoja de Russell y Teoría de Conjuntos", category: "Matemáticas" },
    { id: "distribucion_normal", name: "El Teorema del Límite Central y Campana de Gauss", category: "Matemáticas" },
    { id: "metodo_montecarlo", name: "Simulaciones por el Método de Montecarlo", category: "Matemáticas" },
    { id: "numeros_complejos", name: "Planos Argand e Identidad de Euler", category: "Matemáticas" },
    { id: "logica_difusa", name: "Lógica Difusa (Fuzzy Logic)", category: "Matemáticas" },
    { id: "sistemas_dinamicos", name: "Atractores Extraños y Caos Determinista", category: "Matemáticas" },
    { id: "criptografia_rsa", name: "Aritmética Modular y Criptografía RSA", category: "Matemáticas" },
    { id: "teoria_catastrofes", name: "Teoría de Catástrofes de René Thom", category: "Matemáticas" },
    { id: "cuatrenios_maternidad", name: "Álgebra de Cuaterniones de Hamilton", category: "Matemáticas" },
    { id: "geometria_proyectiva", name: "Principios de Geometría Proyectiva", category: "Matemáticas" },
    { id: "paradoja_banach_tarski", name: "La Paradoja de Banach-Tarski", category: "Matemáticas" },
    { id: "teoria_informacion_shannon", name: "Entropía de la Información según Claude Shannon", category: "Matemáticas" },
    { id: "cálculo_variaciones", name: "Ecuaciones de Euler-Lagrange", category: "Matemáticas" },
    { id: "combinatoria_pigeonhole", name: "El Principio del Palomar", category: "Matemáticas" },
    { id: "matrices_markov", name: "Cadenas de Markov y Procesos Estocásticos", category: "Matemáticas" },
    { id: "solidos_platonicos", name: "Geometría de los Poliedros Regulares", category: "Matemáticas" },

    // --- INFORMÁTICA E INTELIGENCIA ARTIFICIAL (40) ---
    { id: "maquina_turing", name: "La Máquina de Turing y la Halting Problem", category: "Tecnología" },
    { id: "redes_neuronales", name: "Arquitectura de Redes Neuronales Artificiales", category: "Inteligencia Artificial" },
    { id: "llm_transformers", name: "Mecanismo de Atención y Modelos Transformer (GPT)", category: "Inteligencia Artificial" },
    { id: "algoritmos_ordenamiento", name: "Complejidad Algorítmica Big O y Quicksort", category: "Informática" },
    { id: "compiladores_interpretes", name: "Diferencia entre Compiladores e Intérpretes", category: "Informática" },
    { id: "computacion_cuantica", name: "Qubits, Superposición y Entrelazamiento", category: "Tecnología" },
    { id: "blockchain_consensual", name: "Mecanismos de Consenso: Proof of Work vs Proof of Stake", category: "Tecnología" },
    { id: "aprendizaje_refuerzo", name: "Aprendizaje por Refuerzo (Q-Learning y RLHF)", category: "Inteligencia Artificial" },
    { id: "vision_computacional", name: "Redes Neuronales Convolucionales (CNN) en Visión", category: "Inteligencia Artificial" },
    { id: "sistemas_operativos_kernel", name: "Estructura del Kernel en Sistemas Operativos", category: "Informática" },
    { id: "bases_datos_nosql", name: "Bases de Datos Relacionales (SQL) vs NoSQL", category: "Informática" },
    { id: "redes_tcp_ip", name: "Modelo OSI y Protocolos TCP/IP", category: "Informática" },
    { id: "gan_redes_adversarias", name: "Redes Generativas Adversarias (GANs)", category: "Inteligencia Artificial" },
    { id: "arquitectura_von_neumann", name: "La Arquitectura de Von Neumann", category: "Informática" },
    { id: "desarrollo_web_http", name: "Evolución de HTTP/1.1 a HTTP/3", category: "Informática" },
    { id: "programacion_funcional", name: "Paradigmas: Programación Funcional vs POO", category: "Informática" },
    { id: "git_control_versiones", name: "Grafos Dirigidos Acíclicos en Git", category: "Informática" },
    { id: "ia_alineacion_etica", name: "El Problema de Alineación de la Inteligencia Artificial", category: "Inteligencia Artificial" },
    { id: "procesamiento_lenguaje_natural", name: "Tokenización y Embeddings de Palabras", category: "Inteligencia Artificial" },
    { id: "sistemas_distribuidos", name: "El Teorema CAP en Sistemas Distribuidos", category: "Informática" },
    { id: "microprocesadores_x86_arm", name: "Arquitecturas RISC vs CISC (ARM vs x86)", category: "Tecnología" },
    { id: "algoritmos_geneticos", name: "Computación Evolutiva y Algoritmos Genéticos", category: "Inteligencia Artificial" },
    { id: "test_turing", name: "El Test de Turing y la Habitación China de Searle", category: "Inteligencia Artificial" },
    { id: "edge_computing", name: "Arquitectura de Edge Computing e IoT", category: "Tecnología" },
    { id: "memoria_virtual_paging", name: "Memoria Virtual, Paginación y Cache Misses", category: "Informática" },
    { id: "grafos_conocimiento", name: "Knowledge Graphs y Ontologías de Datos", category: "Inteligencia Artificial" },
    { id: "compresion_datos_huffman", name: "Algoritmos de Compresión con y sin Pérdida", category: "Informática" },
    { id: "realidad_aumentada_optica", name: "Principios de Posicionamiento SLAM en AR/VR", category: "Tecnología" },
    { id: "agentes_autonomos", name: "Arquitectura de Agentes Inteligentes Multiagente", category: "Inteligencia Artificial" },
    { id: "webassembly", name: "WebAssembly (Wasm) y Computación en Navegadores", category: "Informática" },
    { id: "maquinas_soporte_vectorial", name: "Support Vector Machines (SVM) en Machine Learning", category: "Inteligencia Artificial" },
    { id: "overfitting_underfitting", name: "Sesgo, Varianza y Regularización (L1/L2)", category: "Inteligencia Artificial" },
    { id: "arquitectura_serverless", name: "Computación Serverless y Funciones como Servicio (FaaS)", category: "Informática" },
    { id: "redes_difusion", name: "Modelos de Difusión en Generación de Imágenes", category: "Inteligencia Artificial" },
    { id: "patrones_diseno_software", name: "Patrones GoF (Gang of Four) en Ingeniería de Software", category: "Informática" },
    { id: "sistemas_recomendacion", name: "Filtrado Colaborativo y Basado en Contenido", category: "Inteligencia Artificial" },
    { id: "hardware_tpu_gpu", name: "Arquitectura Interna de las GPUs para Tensor Core", category: "Tecnología" },
    { id: "protocolo_dns", name: "Resolución Dominio-IP y Propagación DNS", category: "Informática" },
    { id: "computacion_neuromorfica", name: "Chips Neuromórficos y Spiking Neural Networks", category: "Tecnología" },
    { id: "teoria_automatas", name: "Autómatas Finitos y Gramáticas Formales de Chomsky", category: "Informática" },

    // --- CIBERSEGURIDAD Y REDES (20) ---
    { id: "criptografia_asimetrica", name: "Criptografía de Llave Pública y Privada", category: "Ciberseguridad" },
    { id: "ataques_ddos", name: "Mecanismos de Ataques DDoS y Mitigación", category: "Ciberseguridad" },
    { id: "ingeniera_social_phishing", name: "Técnicas de Ingeniería Social y Phishing", category: "Ciberseguridad" },
    { id: "vulnerabilidades_owasp", name: "Las 10 Vulnerabilidades Más Críticas de OWASP", category: "Ciberseguridad" },
    { id: "zero_trust", name: "Arquitectura de Seguridad Zero Trust", category: "Ciberseguridad" },
    { id: "ransomware_mecanica", name: "Análisis y Cifrado en Ataques Ransomware", category: "Ciberseguridad" },
    { id: "firewalls_ids", name: "Sistemas de Detección de Intrusos (IDS) y Firewalls", category: "Ciberseguridad" },
    { id: "red_tor_onion", name: "Enrutamiento Cebolla (Onion Routing) y la Dark Web", category: "Ciberseguridad" },
    { id: "man_in_the_middle", name: "Ataques Man-in-the-Middle y Certificados TLS", category: "Ciberseguridad" },
    { id: "buffer_overflow", name: "Desbordamiento de Búfer y Seguridad en Memoria", category: "Ciberseguridad" },
    { id: "steganografia", name: "Ocultamiento de Datos con Esteganografía", category: "Ciberseguridad" },
    { id: "criptografia_post_cuantica", name: "Algoritmos Criptográficos Post-Cuánticos", category: "Ciberseguridad" },
    { id: "pen_testing_red_team", name: "Metodologías de Penetration Testing", category: "Ciberseguridad" },
    { id: "hashes_sha_md5", name: "Funciones Hash Unidireccionales y Colisiones", category: "Ciberseguridad" },
    { id: "autenticacion_jwt_oauth", name: "Protocolos OAuth 2.0 y Tokens JWT", category: "Ciberseguridad" },
    { id: "malware_analisis_reverse", name: "Ingeniería Inversa de Malware en Sanboxes", category: "Ciberseguridad" },
    { id: "seguridad_firmware_tpm", name: "Módulos de Plataforma Segura (TPM) y Root of Trust", category: "Ciberseguridad" },
    { id: "sql_injection", name: "Mecanismo y Prevención de Inyecciones SQL", category: "Ciberseguridad" },
    { id: "zero_day_exploits", name: "Mercados y Mitigación de Exploits Zero-Day", category: "Ciberseguridad" },
    { id: "biometria_seguridad", name: "Sistemas Biométricos y Tasa de Falsos Aceptos", category: "Ciberseguridad" },

    // --- FILOSOFÍA (35) ---
    { id: "estoicismo", name: "Principios de la Filosofía Estoica", category: "Filosofía" },
    { id: "alegoria_caverna", name: "La Alegoría de la Caverna de Platón", category: "Filosofía" },
    { id: "imperativo_categorico", name: "El Imperativo Categórico de Immanuel Kant", category: "Filosofía" },
    { id: "existencialismo_sartre", name: "Existencialismo: Sartre, Camus y Beauvoir", category: "Filosofía" },
    { id: "utilitarismo_bentham", name: "Utilitarismo: Jeremy Bentham y John Stuart Mill", category: "Filosofía" },
    { id: "superhombre_nietzsche", name: "El Superhombre y la Muerte de Dios en Nietzsche", category: "Filosofía" },
    { id: "empirismo_vs_racionalismo", name: "Empirismo (Hume) vs Racionalismo (Descartes)", category: "Filosofía" },
    { id: "dialéctica_hegeliana", name: "Tesis, Antítesis y Síntesis en Hegel", category: "Filosofía" },
    { id: "contrato_social", name: "Teoría del Contrato Social: Hobbes, Locke y Rousseau", category: "Filosofía" },
    { id: "epistemologia_popper", name: "El Falsacionismo de Karl Popper", category: "Filosofía" },
    { id: "paradigmas_kuhn", name: "Estructura de las Revoluciones Científicas de Thomas Kuhn", category: "Filosofía" },
    { id: "filosofia_mente_zombis", name: "El Problema Duro de la Conciencia y Zombis Filosóficos", category: "Filosofía" },
    { id: "etica_virtud_aristoteles", name: "La Ética a Nicómaco de Aristóteles", category: "Filosofía" },
    { id: "nihilismo", name: "Nihilismo Pasivo vs Nihilismo Activo", category: "Filosofía" },
    { id: "postmodernismo_foucault", name: "Poder y Biopolítica en Michel Foucault", category: "Filosofía" },
    { id: "filosofia_taoista", name: "Taoísmo: El Wu Wei y el Tao Te Ching", category: "Filosofía" },
    { id: "filosofia_confucianismo", name: "Los Cinco Enfoques del Confucianismo", category: "Filosofía" },
    { id: "solipsismo", name: "El Solipsismo y el Escepticismo Radical", category: "Filosofía" },
    { id: "experimento_dilema_tranvia", name: "El Dilema del Tranvía y la Ética Experimental", category: "Filosofía" },
    { id: "filosofia_analitica_wittgenstein", name: "Tractatus Logico-Philosophicus de Wittgenstein", category: "Filosofía" },
    { id: "cinismo_diogenes", name: "La Filosofía Cínica de Diógenes de Sinope", category: "Filosofía" },
    { id: "epicureismo", name: "Epicureísmo: El Placer Moderado y la Ataraxia", category: "Filosofía" },
    { id: "fenomenologia_husserl", name: "La Fenomenología de Husserl y Heidegger", category: "Filosofía" },
    { id: "velo_ignorancia_rawls", name: "La Teoría de la Justicia y el Velo de Ignorancia de Rawls", category: "Filosofía" },
    { id: "escuela_frankfurt", name: "Teoría Crítica de la Escuela de Frankfurt", category: "Filosofía" },
    { id: "desconstruccion_derrida", name: "La Deconstrucción de Jacques Derrida", category: "Filosofía" },
    { id: "vitalismo_bergson", name: "El Élan Vital de Henri Bergson", category: "Filosofía" },
    { id: "schopenhauer_voluntad", name: "El Mundo como Voluntad y Representación de Schopenhauer", category: "Filosofía" },
    { id: "filosofia_tecnologia", name: "La Pregunta por la Técnica según Martin Heidegger", category: "Filosofía" },
    { id: "filosofia_materia_spinoza", name: "El Panteísmo de Baruch Spinoza", category: "Filosofía" },
    { id: "metafisica_monadas", name: "La Monadología de Gottfried Leibniz", category: "Filosofía" },
    { id: "transhumanismo_etica", name: "Debates Éticos en el Transhumanismo", category: "Filosofía" },
    { id: "pragmatismo_peirce", name: "Pragmatismo: Peirce, James y Dewey", category: "Filosofía" },
    { id: "filosofia_ubuntu", name: "La Filosofía Africana Ubuntu", category: "Filosofía" },
    { id: "navaja_ockham", name: "La Navaja de Ockham y la Parsimonia", category: "Filosofía" },

    // --- HISTORIA UNIVERSAL (45) ---
    { id: "revolucion_francesa", name: "La Revolución Francesa y el Terror", category: "Historia" },
    { id: "imperio_romano_caida", name: "Factores de la Caída del Imperio Romano de Occidente", category: "Historia" },
    { id: "segunda_guerra_mundial", name: "Orígenes y Cusas de la Segunda Guerra Mundial", category: "Historia" },
    { id: "revolucion_industrial", name: "La Primera y Segunda Revolución Industrial", category: "Historia" },
    { id: "antiguo_egipto_imperios", name: "El Periodo Amarna y el Monoteísmo de Akenatón", category: "Historia" },
    { id: "mesopotamia_sumeria", name: "Sumeria y el Código de Hammurabi", category: "Historia" },
    { id: "guerra_fria_crisis_misiles", name: "La Crisis de los Misiles en Cuba (1962)", category: "Historia" },
    { id: "imperio_mongol", name: "Conquistas e Impacto del Imperio Mongol de Genghis Khan", category: "Historia" },
    { id: "revolucion_rusa", name: "La Revolución Bolchevique de 1917", category: "Historia" },
    { id: "imperio_bizantino", name: "Caída de Constantinopla en 1453", category: "Historia" },
    { id: "guerras_medicas", name: "Las Guerras Médicas: Grecia vs Persia", category: "Historia" },
    { id: "peste_negra", name: "La Peste Negra y sus Consecuencias Socioeconómicas", category: "Historia" },
    { id: "independencia_eeuu", name: "La Guerra de Independencia de los EE.UU.", category: "Historia" },
    { id: "imperio_incaico", name: "Estructura Organizativa del Tawantinsuyu", category: "Historia" },
    { id: "civilizacion_maya", name: "Colapso Maya del Periodo Clásico", category: "Historia" },
    { id: "guerras_punicas", name: "Las Guerras Púnicas: Roma vs Cártago", category: "Historia" },
    { id: "renacimiento_florencia", name: "El Renacimiento y la Familia Médici", category: "Historia" },
    { id: "reforma_protestante", name: "Lutero y las 95 Tesis en la Reforma Protestante", category: "Historia" },
    { id: "imperio_otomano", name: "Expansión y Apogeo del Imperio Otomano", category: "Historia" },
    { id: "guerra_treinta_anos", name: "La Guerra de los Treinta Años y la Paz de Westfalia", category: "Historia" },
    { id: "revolucion_haitiana", name: "La Revolución Haitiana (1791–1804)", category: "Historia" },
    { id: "descolonizacion_africa", name: "La Conferencia de Berlín y el Reparto de África", category: "Historia" },
    { id: "imperio_azteca", name: "La Caída de Tenochtitlán en 1521", category: "Historia" },
    { id: "dinastia_han", name: "La Dinastía Han y la Apertura de la Ruta de la Seda", category: "Historia" },
    { id: "primera_guerra_mundial", name: "El Sistema de Alianzas y la Guerra de Trincheras", category: "Historia" },
    { id: "imperio_carolingio", name: "Charlemagne y el Imperio Carolingio", category: "Historia" },
    { id: "guerra_civil_espanola", name: "Causas y Desarrollo de la Guerra Civil Española", category: "Historia" },
    { id: "primavera_pueblos_1848", name: "Las Revoluciones de 1848 en Europa", category: "Historia" },
    { id: "periodo_sengoku_japon", name: "Unificación de Japón: Oda Nobunaga y Tokugawa", category: "Historia" },
    { id: "aparthied_sudafrica", name: "Historia y Fin del Apartheid en Sudáfrica", category: "Historia" },
    { id: "guerras_napoleonicas", name: "Campañas Napoleónicas y el Código Civil", category: "Historia" },
    { id: "guerra_vietnam", name: "Geopolítica de la Guerra de Vietnam", category: "Historia" },
    { id: "expansion_islamica", name: "El Califato de Córdoba y la Edad de Oro del Islam", category: "Historia" },
    { id: "cruzadas_oriente", name: "Impacto Socioeconómico de Las Cruzadas", category: "Historia" },
    { id: "caida_muro_berlin", name: "La Caída del Muro de Berlín y el Fin del Bloque Soviético", category: "Historia" },
    { id: "independencias_hispanoamericanas", name: "Campañas de Bolívar y San Martín en América", category: "Historia" },
    { id: "guerras_opio", name: "Las Guerras del Opio y los Tratados Desiguales en China", category: "Historia" },
    { id: "gran_depresion_1929", name: "El Crack del 29 y la Gran Depresión", category: "Historia" },
    { id: "restauracion_meiji", name: "La Revolución/Restauración Meiji en Japón", category: "Historia" },
    { id: "civilizacion_valle_indo", name: "Mohenjo-Daro y la Civilización del Valle del Indo", category: "Historia" },
    { id: "guerra_rosas", name: "La Guerra de las Dos Rosas en Inglaterra", category: "Historia" },
    { id: "revolucion_cultural_china", name: "La Gran Revolución Cultural Proletaria de Mao", category: "Historia" },
    { id: "historia_cartago", name: "Navegación y Comercio Fenicio en el Mediterráneo", category: "Historia" },
    { id: "imperio_mali", name: "Mansa Musa y la Riqueza del Imperio de Malí", category: "Historia" },
    { id: "guerra_corea", name: "La Guerra de Corea y el Paralelo 38", category: "Historia" },

    // --- PSICOLOGÍA (30) ---
    { id: "sesgos_cognitivos", name: "Sesgos Cognitivos: Confirmación, Anclaje y Dunning-Kruger", category: "Psicología" },
    { id: "condicionamiento_pavlov", name: "Condicionamiento Clásico vs Operante (Skinner)", category: "Psicología" },
    { id: "experimento_milgram", name: "El Experimento de Milgram sobre la Obediencia", category: "Psicología" },
    { id: "prision_stanford", name: "El Experimento de la Prisión de Stanford", category: "Psicología" },
    { id: "psicoanalisis_freud", name: "El Ello, el Yo y el Superyó de Freud", category: "Psicología" },
    { id: "arquetipos_jung", name: "El Inconsciente Colectivo y Arquetipos de Carl Jung", category: "Psicología" },
    { id: "psicologia_gestalt", name: "Principios de Percepción de la Psicología de la Gestalt", category: "Psicología" },
    { id: "teoria_apego", name: "Teoría del Apego: Bowlby y Ainsworth", category: "Psicología" },
    { id: "desarrollo_piaget", name: "Etapas del Desarrollo Cognitivo de Jean Piaget", category: "Psicología" },
    { id: "disonancia_cognitiva", name: "La Teoría de la Disonancia Cognitiva de Festinger", category: "Psicología" },
    { id: "terapia_cognitivo_conductual", name: "Principios de la Terapia Cognitivo-Conductual (TCC)", category: "Psicología" },
    { id: "piramide_maslow", name: "La Jerarquía de Necesidades de Maslow", category: "Psicología" },
    { id: "efecto_espectador", name: "Efecto Espectador y Difusión de la Responsabilidad", category: "Psicología" },
    { id: "inteligencia_emocional", name: "El Modelo de Inteligencia Emocional de Daniel Goleman", category: "Psicología" },
    { id: "desesperanza_aprendida", name: "La Desesperanza Aprendida de Martin Seligman", category: "Psicología" },
    { id: "psicologia_positiva", name: "El Modelo PERMA de la Psicología Positiva", category: "Psicología" },
    { id: "trastornos_personalidad", name: "Cluster A, B y C de los Trastornos de Personalidad", category: "Psicología" },
    { id: "memoria_falsa", name: "Implante de Falsos Recuerdos por Elizabeth Loftus", category: "Psicología" },
    { id: "teoria_mente", name: "Desarrollo de la Teoría de la Mente en Niños", category: "Psicología" },
    { id: "efecto_halo", name: "El Efecto Halo y Atracción Interpersonal", category: "Psicología" },
    { id: "pensamiento_rapido_lento", name: "Sistema 1 y Sistema 2 de Daniel Kahneman", category: "Psicología" },
    { id: "neurosis_psicosis", name: "Diferenciación Clínica entre Neurosis y Psicosis", category: "Psicología" },
    { id: "psicologia_evolutiva", name: "Psicología Evolutiva y Selección Sexual", category: "Psicología" },
    { id: "conformidad_asch", name: "El Experimento de Conformidad de Solomon Asch", category: "Psicología" },
    { id: "flow_csikszentmihalyi", name: "El Estado de Flujo (Flow) de Csíkszentmihályi", category: "Psicología" },
    { id: "efecto_pygmalion", name: "El Efecto Pigmalión en la Educación", category: "Psicología" },
    { id: "teoria_vygotsky", name: "La Zona de Desarrollo Próximo de Lev Vygotsky", category: "Psicología" },
    { id: "resiliencia_mecanismos", name: "Mecanismos Psicológicos de la Resiliencia", category: "Psicología" },
    { id: "psicofisiologia_estres", name: "Eje HPA y Fisiología del Estrés Crónico", category: "Psicología" },
    { id: "sindrome_impostor", name: "Dinámica Psicológica del Síndrome del Impostor", category: "Psicología" },

    // --- ECONOMÍA Y FINANZAS (30) ---
    { id: "oferta_demanda", name: "Ley de la Oferta y la Demanda y Elasticidad", category: "Economía" },
    { id: "inflacion_hiperinflacion", name: "Causas de la Inflación y Políticas Monetarias", category: "Economía" },
    { id: "mano_invisible", name: "La Mano Invisible de Adam Smith", category: "Economía" },
    { id: "keynesianismo_vs_monetarismo", name: "Escuela Keynesiana vs Escuela Monetarista (Friedman)", category: "Economía" },
    { id: "escuela_austriaca", name: "La Escuela Austríaca de Economía (Hayek y Mises)", category: "Economía" },
    { id: "marxismo_plusvalia", name: "El Capital de Marx y el Concepto de Plusvalía", category: "Economía" },
    { id: "bancos_centrales", name: "Funcionamiento de la Reserva Federal y Bancos Centrales", category: "Economía" },
    { id: "ventaja_comparativa", name: "Comercio Internacional y Ventaja Comparativa de Ricardo", category: "Economía" },
    { id: "tragedia_comunes", name: "La Tragedia de los Bienes Comunes", category: "Economía" },
    { id: "finanzas_conductuales", name: "Teoría de las Perspectivas en Finanzas Conductuales", category: "Economía" },
    { id: "burbujas_financieras", name: "La Burbuja de los Tulipanes y la Burbuja Dot-Com", category: "Economía" },
    { id: "criterio_paretto", name: "Eficiencia de Pareto y Distribución de Riqueza", category: "Economía" },
    { id: "politica_fiscal", name: "Déficit Fiscal, Impuestos y Curva de Laffer", category: "Economía" },
    { id: "sistema_reserva_fraccionaria", name: "Creación de Dinero y Reserva Fraccionaria", category: "Economía" },
    { id: "criptoeconomia", name: "Incentivos Económicos en Criptoeconomía", category: "Economía" },
    { id: "pib_medicion", name: "Cálculo del PIB y sus Limitaciones Estadísticas", category: "Economía" },
    { id: "monopolios_oligopolios", name: "Estructuras de Mercado: Monopolios vs Oligopolios", category: "Economía" },
    { id: "microcreditos_yunus", name: "Economía Social y Microcréditos de Muhammad Yunus", category: "Economía" },
    { id: "teoria_juegos_subastas", name: "Diseño de Subastas y la Malla de Vickrey", category: "Economía" },
    { id: "deuda_soberana", name: "Mecanismos de Deuda Soberana y Default", category: "Economía" },
    { id: "patron_oro_bretton_woods", name: "El Fin del Patrón Oro y los Acuerdos de Bretton Woods", category: "Economía" },
    { id: "desigualdad_piketty", name: "El Capital en el Siglo XXI de Thomas Piketty", category: "Economía" },
    { id: "economia_circular", name: "Principios de la Economía Circular", category: "Economía" },
    { id: "efecto_cantillon", name: "Inyección de Dinero y el Efecto Cantillon", category: "Economía" },
    { id: "derivadados_financieros", name: "Opciones, Futuros y Swaps Financieros", category: "Economía" },
    { id: "pobreza_trampas", name: "Trampas de Pobreza y Economía del Desarrollo", category: "Economía" },
    { id: "renta_basica_universal", name: "Modelos Teóricos de Renta Básica Universal", category: "Economía" },
    { id: "teoria_monetaria_moderna", name: "La Teoría Monetaria Moderna (MMT)", category: "Economía" },
    { id: "externalidades_pigou", name: "Externalidades Negativas e Impuestos Pigouvianos", category: "Economía" },
    { id: "index_funds_bogle", name: "Inversión Pasiva y la Hipótesis del Mercado Eficiente", category: "Economía" },

    // --- CIENCIAS POLÍTICAS Y DERECHO (25) ---
    { id: "separacion_poderes", name: "Separación de Poderes de Montesquieu", category: "Ciencias Políticas" },
    { id: "maquiavelo_principe", name: "El Realismo Político en El Príncipe de Maquiavelo", category: "Ciencias Políticas" },
    { id: "sistemas_electorales", name: "Sistemas Mayoritarios vs Proporcionales (D'Hondt)", category: "Ciencias Políticas" },
    { id: "totalitarismo_arendt", name: "Los Orígenes del Totalitarismo de Hannah Arendt", category: "Ciencias Políticas" },
    { id: "derechos_humanos_declaracion", name: "Origen de la Declaración Universal de Derechos Humanos", category: "Derecho" },
    { id: "soft_power_hard_power", name: "Poder Blando vs Poder Duro en Relaciones Internacionales", category: "Ciencias Políticas" },
    { id: "geopolitica_spykman", name: "Teoría del Heartland (Mackinder) y Rimland", category: "Ciencias Políticas" },
    { id: "common_law_vs_civil_law", name: "Derecho Anglosajón (Common Law) vs Derecho Continental", category: "Derecho" },
    { id: "soberania_bodin", name: "El Concepto de Soberanía Estatal", category: "Ciencias Políticas" },
    { id: "democracia_ateniense", name: "Mecanismos de la Democracia Directa Ateniense", category: "Ciencias Políticas" },
    { id: "fascismo_ideologia", name: "Bases Ideológicas del Fascismo e Imperialismo", category: "Ciencias Políticas" },
    { id: "onu_consejo_seguridad", name: "Estructura y Derecho de Veto en la ONU", category: "Ciencias Políticas" },
    { id: "derecho_internacional_humanitario", name: "Los Convenios de Ginebra", category: "Derecho" },
    { id: "anarquismo_teoria", name: "Teoría Anarquista: Kropotkin y Bakunin", category: "Ciencias Políticas" },
    { id: "populismo_teoria", name: "Teoría del Populismo según Ernesto Laclau", category: "Ciencias Políticas" },
    { id: "lobbying_politica", name: "Lobbying y Regulación de Grupos de Interés", category: "Ciencias Políticas" },
    { id: "habeas_corpus", name: "El Principio de Habeas Corpus en la Historia", category: "Derecho" },
    { id: "trampa_tucidides", name: "La Trampa de Tucídides en Geopolítica", category: "Ciencias Políticas" },
    { id: "federalismo_vs_centralismo", name: "Sistemas Federales vs Centralistas de Gobierno", category: "Ciencias Políticas" },
    { id: "tribunal_penal_internacional", name: "El Estatuto de Roma y la Corte Penal Internacional", category: "Derecho" },
    { id: "constitucionalismo", name: "Control de Constitucionalidad y Juicio de Amparo", category: "Derecho" },
    { id: "propiedad_intelectual", name: "Patentes, Marcas y Derecho de Autor (Copyright)", category: "Derecho" },
    { id: "tecnocracia", name: "Modelos Tecnocráticos de Gobernanza", category: "Ciencias Políticas" },
    { id: "guerra_hibrida", name: "Guerra Híbrida y Desinformación Geopolítica", category: "Ciencias Políticas" },
    { id: "jurisprudencia_marbury", name: "Marbury v. Madison y la Revisión Judicial", category: "Derecho" },

    // --- SOCIOLOGÍA Y ANTROPOLOGÍA (20) ---
    { id: "suicidio_durkheim", name: "El Estudio del Suicidio de Émile Durkheim", category: "Sociología" },
    { id: "capital_cultural_bourdieu", name: "Habitus y Capital Cultural en Pierre Bourdieu", category: "Sociología" },
    { id: "modernidad_liquida", name: "La Modernidad Líquida de Zygmunt Bauman", category: "Sociología" },
    { id: "panoptico_bentham", name: "El Panóptico y la Sociedad de la Vigilancia", category: "Sociología" },
    { id: "antropologia_estructuralista", name: "Claude Lévi-Strauss y el Estructuralismo Antropológico", category: "Antropología" },
    { id: "evoluciom_hominidos", name: "Línea Evolutiva Humana: De Australopithecus a Homo Sapiens", category: "Antropología" },
    { id: "construccion_social_realidad", name: "La Construcción Social de la Realidad (Berger y Luckmann)", category: "Sociología" },
    { id: "etnografia_observacion", name: "Métodos Etnográficos y Descripción Densa de Geertz", category: "Antropología" },
    { id: "sociedad_riesgo", name: "La Sociedad del Riesgo de Ulrich Beck", category: "Sociología" },
    { id: "interaccionismo_simbolico", name: "Interaccionismo Simbólico de George Herbert Mead", category: "Sociología" },
    { id: "teoria_redes_sociales", name: "La Fuerza de los Lazos Débiles de Mark Granovetter", category: "Sociología" },
    { id: "kula_ring", name: "El Intercambio Kula y la Antropología Económica (Malinowski)", category: "Antropología" },
    { id: "estratificacion_social", name: "Sistemas de Castas vs Sistemas de Clases Sociales", category: "Sociología" },
    { id: "hipotesis_sapir_whorf", name: "Relativismo Lingüístico (Sapir-Whorf)", category: "Antropología" },
    { id: "gentrificacion_urbana", name: "Sociología Urbana y Fenómenos de Gentrificación", category: "Sociología" },
    { id: "hipotesis_simios_acuaticos", name: "Hipótesis Antropológicas sobre el Bipedismo", category: "Antropología" },
    { id: "tabu_incesto", name: "Universalidad y Explicaciones del Tabú del Incesto", category: "Antropología" },
    { id: "hiperconsumismo", name: "La Sociedad del Consumo según Jean Baudrillard", category: "Sociología" },
    { id: "anomia_social", name: "Anomia Social en Épocas de Transformación", category: "Sociología" },
    { id: "subculturas_tribus_urbanas", name: "Teoría Sociológica de las Subculturas", category: "Sociología" },

    // --- LITERATURA Y LINGÜÍSTICA (25) ---
    { id: "camino_heroe", name: "El Monomito y el Camino del Héroe de Joseph Campbell", category: "Literatura" },
    { id: "gramatica_generativa", name: "La Gramática Generativa Transformacional de Chomsky", category: "Lingüística" },
    { id: "realismo_magico", name: "Cien Años de Soledad y el Realismo Mágico", category: "Literatura" },
    { id: "tragedia_griega", name: "La Poética de Aristóteles y la Tragedia Griega", category: "Literatura" },
    { id: "semiotica_saussure", name: "Significante y Significado en Ferdinand de Saussure", category: "Lingüística" },
    { id: "ulises_joyce", name: "El Monólogo Interior y el Ulises de James Joyce", category: "Literatura" },
    { id: "existencialismo_literario", name: "La Metamorfosis de Kafka y el Absurdo", category: "Literatura" },
    { id: "sociolingüística", name: "Variación Lingüística, Dialectos y Registros", category: "Lingüística" },
    { id: "romanticismo_vs_ilustracion", name: "El Movimiento Romántico Sturm und Drang", category: "Literatura" },
    { id: "teoria_iceberg_hemingway", name: "La Teoría del Témpano de Hielo de Hemingway", category: "Literatura" },
    { id: "pragmatica_actos_habla", name: "Teoría de los Actos de Habla (Austin y Searle)", category: "Lingüística" },
    { id: "don_quijote_modernidad", name: "Don Quijote y el Nacimiento de la Novela Moderna", category: "Literatura" },
    { id: "etimologia_protoindoeuropeo", name: "La Reconstrucción del Idioma Protoindoeuropeo", category: "Lingüística" },
    { id: "distopias_siglo_xx", name: "Orwell (1984) vs Huxley (Un Mundo Feliz)", category: "Literatura" },
    { id: "generacion_27", name: "La Poesía Vanguardista de la Generación del 27", category: "Literatura" },
    { id: "dante_divina_comedia", name: "Estructura Poética de La Divina Comedia", category: "Literatura" },
    { id: "fonetica_fonologia", name: "Aparato Fonador y el Alfabeto Fonético Internacional (IPA)", category: "Lingüística" },
    { id: "teatro_absurdo", name: "Esperando a Godot y el Teatro del Absurdo", category: "Literatura" },
    { id: "literatura_rusa_dostoyevski", name: "La Psicología del Pecado en Crimen y Castigo", category: "Literatura" },
    { id: "haiku_poesia_japonesa", name: "Métrica y Estética del Haiku Tradicional", category: "Literatura" },
    { id: "intertextualidad_genette", name: "La Intertextualidad y Paratextos de Gérard Genette", category: "Literatura" },
    { id: "epopeya_gilgamesh", name: "El Poema de Gilgamesh y el Mito del Diluvio", category: "Literatura" },
    { id: "desplazamiento_semantico", name: "Evolución Semántica: Metáfora y Metonimia en Lenguaje", category: "Lingüística" },
    { id: "boom_latinoamericano", name: "Causas e Impacto del Boom Latinoamericano", category: "Literatura" },
    { id: "neurociencia_lectura", name: "Procesos Cognitivos de la Lectura en el Cerebro", category: "Lingüística" },

    // --- ARTE Y ARQUITECTURA (25) ---
    { id: "perspectiva_lineal_renacimiento", name: "La Invención de la Perspectiva por Brunelleschi", category: "Arte" },
    { id: "impresionismo_luz", name: "El Impresionismo y la Captura de la Luz (Monet, Renoir)", category: "Arte" },
    { id: "cubismo_picasso", name: "Descomposición de la Forma: Cubismo Analítico y Sintético", category: "Arte" },
    { id: "arquitectura_gotica", name: "Arcos Ojivales y Arbotantes en la Arquitectura Gótica", category: "Arquitectura" },
    { id: "bauhaus_diseno", name: "La Escuela Bauhaus: La Forma Sigue a la Función", category: "Arte" },
    { id: "barroco_claroscuro", name: "Tenebrismo y Claroscuro en Caravaggio y Rembrandt", category: "Arte" },
    { id: "surrealismo_dalí", name: "Automatismo y el Método Paranoico-Crítico", category: "Arte" },
    { id: "brutalismo_arquitectura", name: "El Movimiento Brutalista y el Hormigón Visto", category: "Arquitectura" },
    { id: "arte_conceptual", name: "Duchamp, los Ready-mades y el Arte Conceptual", category: "Arte" },
    { id: "proporcion_aurea_arte", name: "Uso de la Proporción Áurea en la Pintura Clásica", category: "Arte" },
    { id: "expresionismo_abstracto", name: "Action Painting: Pollock y Mark Rothko", category: "Arte" },
    { id: "ordenes_arquitectonicos_griegos", name: "Órdenes Dórico, Jónico y Corintio", category: "Arquitectura" },
    { id: "pop_art_warhol", name: "Andy Warhol y la Crítica al Consumismo en el Pop Art", category: "Arte" },
    { id: "arquitectura_paramétrica", name: "Zaha Hadid y el Diseño Paramétrico", category: "Arquitectura" },
    { id: "muralismo_mexicano", name: "Rivera, Orozco y Siqueiros en el Muralismo", category: "Arte" },
    { id: "arte_bizantino_mosaicos", name: "La Iconografía Mística en los Mosaicos Bizantinos", category: "Arte" },
    { id: "art_nouveau", name: "Líneas Orgánicas en el Art Nouveau y Gaudí", category: "Arte" },
    { id: "land_art", name: "Intervenciones del Land Art en la Naturaleza", category: "Arte" },
    { id: "urbanismo_haussmann", name: "La Transformación Haussmanniana de París", category: "Arquitectura" },
    { id: "street_art_banksy", name: "Graffiti, Estarcido y Arte Urbano Político", category: "Arte" },
    { id: "constructivismo_ruso", name: "Arte al Servicio de la Revolución: Constructivismo", category: "Arte" },
    { id: "arquitectura_bioclimatica", name: "Principios de Diseño Pasivo y Bioclimático", category: "Arquitectura" },
    { id: "ukiyo_e", name: "Grabados Japoneses Ukiyo-e y la Estampa Flotante", category: "Arte" },
    { id: "minimalismo_escultura", name: "El Minimalismo Escultórico de Donald Judd", category: "Arte" },
    { id: "teoria_color_goethe", name: "Teoría del Color de Goethe vs Isaac Newton", category: "Arte" },

    // --- MÚSICA Y ARTES ESCÉNICAS (20) ---
    { id: "temperamento_igual", name: "Física del Temperamento Igual y Afinación", category: "Música" },
    { id: "fuga_bach", name: "La Estructura Contrapuntística de la Fuga en Bach", category: "Música" },
    { id: "nacimiento_jazz", name: "Del Blues de Nueva Orleans al Bebop", category: "Música" },
    { id: "atonalismo_schoenberg", name: "El Dodecafonismo y la Músia Atonal", category: "Música" },
    { id: "orquesta_sinfonica_secciones", name: "Evolución y Disposición de la Orquesta Sinfónica", category: "Música" },
    { id: "opera_wagner_leitmotiv", name: "El Leitmotiv y la Obra de Arte Total (Gesamtkunstwerk)", category: "Música" },
    { id: "historia_rock_psicodelico", name: "La Revolución Sonora del Rock Psicodélico de los 60", category: "Música" },
    { id: "musica_electroacustica", name: "La Musique Concrète de Pierre Schaeffer", category: "Música" },
    { id: "tecnica_stanislavski", name: "El Método de Actuación de Stanislavski", category: "Música" },
    { id: "ritmos_polirritmia_africana", name: "Estructura de Polirritmias en la Música Africana", category: "Música" },
    { id: "sintetizadores_moog", name: "Síntesis Sustractiva y el Sintetizador Moog", category: "Música" },
    { id: "historia_hiphop_sampling", name: "La Cultura del Breakbeat y el Sampling en el Hip-Hop", category: "Música" },
    { id: "forma_sonata", name: "Exposición, Desarrollo y Reexposición en la Forma Sonata", category: "Música" },
    { id: "canto_gregoriano", name: "Monofonía y Neumas en el Canto Gregoriano", category: "Música" },
    { id: "teatro_epico_brecht", name: "El Efecto de Distanciamiento en Bertolt Brecht", category: "Música" },
    { id: "gamelan_balines", name: "Escalas Pelog y Slendro en el Gamelán de Indonesia", category: "Música" },
    { id: "flamenco_compas", name: "Estructura del Compás y Estilos (Palos) en el Flamenco", category: "Música" },
    { id: "montaje_cinematografico_eisenstein", name: "Teoría del Montaje Intelectual de Sergei Eisenstein", category: "Música" },
    { id: "acustica_salas", name: "Tiempo de Reverberación (RT60) en Diseño Acústico", category: "Música" },
    { id: "minimalismo_reich", name: "Música Minimalista: Steve Reich y Philip Glass", category: "Música" },

    // --- MITOLOGÍA, RELIGIONES Y CULTURA (25) ---
    { id: "mitologia_griega_panteon", name: "Los 12 Dioses Olímpicos y la Cosmogonía Griega", category: "Cultura" },
    { id: "budismo_cuatro_verdades", name: "Las Cuatro Nobles Verdades y el Noble Camino Óctuple", category: "Cultura" },
    { id: "mitologia_nordica_ragnarok", name: "Escatología Nórdica y el Ragnarök", category: "Cultura" },
    { id: "hinduismo_karma_dharma", name: "Conceptos de Karma, Dharma y Samsara", category: "Cultura" },
    { id: "mitologia_egipcia_osiris", name: "El Mito de Osiris y el Juicio del Alma", category: "Cultura" },
    { id: "tao_te_ching", name: "El Concepto del Yin y el Yang en el Taoísmo", category: "Cultura" },
    { id: "mitologia_mesopotamica_enuma_elish", name: "El Enûma Elish y la Creación Babilonia", category: "Cultura" },
    { id: "cabala_judia", name: "El Árbol de la Vida en la CÁbala Mística", category: "Cultura" },
    { id: "shinto_kamis", name: "El Shintoísmo Japonés y la Veneración a los Kami", category: "Cultura" },
    { id: "mitologia_azteca_soles", name: "La Leyenda de los Cinco Soles", category: "Cultura" },
    { id: "sufismo_misticismo", name: "La Poesía Mística de Rumi y el Sufismo", category: "Cultura" },
    { id: "popol_vuh", name: "El Popol Vuh y la Mitología Maya de la Creación", category: "Cultura" },
    { id: "paganismo_celta", name: "Druidismo y Fiestas Solares Celtas (Samhain, Beltane)", category: "Cultura" },
    { id: "gnosticismo", name: "El Demiurgo y la Salvia Gnóstica", category: "Cultura" },
    { id: "zoroastrismo", name: "Ahura Mazda y el Dualismo del Zoroastrismo", category: "Cultura" },
    { id: "mitologia_romana_sincretismo", name: "Sincretismo entre la Mitología Romana y Griega", category: "Cultura" },
    { id: "jainismo_ahimsa", name: "El Principio de Ahimsa (No Violencia) en el Jainismo", category: "Cultura" },
    { id: "mitologia_inca_viracocha", name: "Viracocha y el Culto al Inti", category: "Cultura" },
    { id: "chamanismo_siberiano", name: "Antropología del Chamanismo Siberiano", category: "Cultura" },
    { id: "cisma_oriente_occidente", name: "El Cisma de 1054 entre la Iglesia Católica y Ortodoxa", category: "Cultura" },
    { id: "mitologia_slava", name: "Perun, Veles y el Panteón Eslavo", category: "Cultura" },
    { id: "sikhismo_principios", name: "Los Cinco K del Sikhismo", category: "Cultura" },
    { id: "mitologia_yoruba", name: "El Sistema de Orishas en la Religión Yoruba", category: "Cultura" },
    { id: "manuscritos_mar_muerto", name: "Importancia de los Manuscritos del Mar Muerto", category: "Cultura" },
    { id: "mitologia_maori", name: "Ranginui y Papatūānuku en la Cosmogonía Māori", category: "Cultura" }
];
